pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                // Checkout the source code from the repository
                checkout scm
            }
        }


         stage('Build taskcenter') {
            steps {
                // Build the Spring Boot application using Maven
                sh 'cd taskcenter && mvn clean package -DskipTests'
            }
        }
	
	 stage('Deploy taskcenter') {
             steps {

                 sh "ssh root@103.255.224.46 'cd /root'"
                 sh "ssh root@103.255.224.46 'rm -rf taskcenter || true'"
                 sh "ssh root@103.255.224.46 'mkdir taskcenter'"
                 
                 sh 'scp -i id_rsa /var/jenkins_home/workspace/taskcenter/taskcenter/target/taskcenter.jar root@103.255.224.46:~/taskcenter/'
                 sh 'scp -i id_rsa /var/jenkins_home/workspace/taskcenter/taskcenter/Dockerfile root@103.255.224.46:~/taskcenter/'

		 sh "ssh root@103.255.224.46 'docker service rm bricknetstack_task-center || true'"
                 sh "ssh root@103.255.224.46 'docker stop root_task-center_1 || true'"
                 sh "ssh root@103.255.224.46 'docker rm root_task-center_1 || true'"
                 sh "ssh root@103.255.224.46 'docker rmi root_task-center_1 || true'"
                 sh "ssh root@103.255.224.46 'docker build -t root_task-center_1 /root/taskcenter'"
                 // sh "ssh root@103.255.224.46 'docker run -it -d -p 9099:9099 --network=root_default --name root_task-center_1 root_task-center_1'"
                 sh "ssh root@103.255.224.46 'docker service create -d -p 9099:9099 --replicas 2 --network=bricknetstack_default --name bricknetstack_task-center root_task-center_1'"
             }
         }        
	
     }
     
  }   
