pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                // Checkout the source code from the repository
                checkout scm
            }
        }


         stage('Build api-gateway') {
            steps {
                // Build the Spring Boot application using Maven
                sh 'echo "1234" | sudo -S mv api-gateway /home/bricknet && cd api-gateway/ && mvn clean package -DskipTests'
            }
        }
	
	 // stage('Deploy api-gateway') {
  //            steps {

  //                sh "ssh root@103.255.224.46 'cd /root'"
  //                sh "ssh root@103.255.224.46 'rm -rf api-gateway || true'"
  //                sh "ssh root@103.255.224.46 'mkdir api-gateway'"
                 
  //                sh 'scp -i id_rsa /var/jenkins_home/workspace/api-gateway/api-gateway/target/api-gateway.jar root@103.255.224.46:~/api-gateway/'
  //                sh 'scp -i id_rsa /var/jenkins_home/workspace/api-gateway/api-gateway/Dockerfile root@103.255.224.46:~/api-gateway/'

		//  sh "ssh root@103.255.224.46 'docker service rm bricknetstack_api-gateway || true'"
  //                sh "ssh root@103.255.224.46 'docker stop root_api-gateway_1 || true'"
  //                sh "ssh root@103.255.224.46 'docker rm root_api-gateway_1 || true'"
  //                sh "ssh root@103.255.224.46 'docker rmi root_api-gateway_1 || true'"
  //                sh "ssh root@103.255.224.46 'docker build -t root_api-gateway_1 /root/api-gateway'"
  //                // sh "ssh root@103.255.224.46 'docker run -it -d -p 9090:9090 --network=root_default --name root_api-gateway_1 root_api-gateway_1'"
		//  sh "ssh root@103.255.224.46 'docker service create -d --name bricknetstack_api-gateway --replicas 2 -p 9090:9090 --network=bricknetstack_default root_api-gateway_1'"
  //            }
  //        }        
	
     }
     
  }   
