pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                // Checkout the source code from the repository
                checkout scm
            }
        }


         stage('Build Eureka-Server') {
            steps {
                // Build the Spring Boot application using Maven
                sh 'cd Eureka-Server && mvn clean package -DskipTests'
            }
        }
	
	 stage('Deploy Eureka-Server') {
             steps {
                 sh "ssh root@103.255.224.46 'cd /root'"
                 sh "ssh root@103.255.224.46 'rm -rf eureka || true'"
                 sh "ssh root@103.255.224.46 'mkdir eureka'"
                 
                 sh ' scp -i id_rsa /var/jenkins_home/workspace/eureka/Eureka-Server/target/eureka.jar root@103.255.224.46:~/eureka/'
                 sh ' scp -i id_rsa /var/jenkins_home/workspace/eureka/Eureka-Server/Dockerfile root@103.255.224.46:~/eureka/'

                 sh "ssh root@103.255.224.46 'docker stop root_eureka_1 || true'"
                 sh "ssh root@103.255.224.46 'docker rm root_eureka_1 || true'"
                 sh "ssh root@103.255.224.46 'docker rmi root_eureka_1 ||true'"
                 sh "ssh root@103.255.224.46 'docker build -t root_eureka_1 /root/eureka'"
                 sh "ssh root@103.255.224.46 'docker run -it -d -p 8761:8761 --name root_eureka_1 root_eureka_1 '"
             }
         }        
	
     }
     
  }   
