server :
  port : 9090

spring :
  application :
    name : API-GATEWAY
  redis :
    host : 192.168.0.9
    port : 6379
  url: redis://192.168.0.9:6379
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
logging :
  level :
    org :
      springframework :
        data :
          redis : DEBUG
    io :
      lettuce :
        core : DEBUG