pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                // Checkout the source code from the repository
                checkout scm
            }
        }


         stage('Build SuperAdmin') {
            steps {
                // Build the Spring Boot application using Maven
                sh 'cd SuperAdmin && mvn clean package -DskipTests'
            }
        }
	
	 stage('Deploy SuperAdmin') {
             steps {

                 sh "ssh root@103.255.224.46 'cd /root'"
                 sh "ssh root@103.255.224.46 'rm -rf superadmin || true'"
                 sh "ssh root@103.255.224.46 'mkdir superadmin'"
                 
                 sh 'scp -i id_rsa /var/jenkins_home/workspace/superadmin/SuperAdmin/target/superadmin.jar root@103.255.224.46:~/superadmin/'
                 sh 'scp -i id_rsa /var/jenkins_home/workspace/superadmin/SuperAdmin/Dockerfile root@103.255.224.46:~/superadmin/'

		 sh "ssh root@103.255.224.46 'docker service rm bricknetstack_superadmin || true'"
                 sh "ssh root@103.255.224.46 'docker stop root_superadmin_1 || true'"
                 sh "ssh root@103.255.224.46 'docker rm root_superadmin_1 || true'"
                 sh "ssh root@103.255.224.46 'docker rmi root_superadmin_1 || true'"
                 sh "ssh root@103.255.224.46 'docker build -t root_superadmin_1 /root/superadmin'"
                 // sh "ssh root@103.255.224.46 'docker run -it -d -p 8081:8081 --network=root_default --name root_superadmin_1 root_superadmin_1'"
                 sh "ssh root@103.255.224.46 'docker service create -d -p 8081:8081 --replicas 2 --network=bricknetstack_default --name bricknetstack_superadmin root_superadmin_1'"

             }
         }        
	
     }
     
  }   
