pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                // Checkout the source code from the repository
                checkout scm
            }
        }


         stage('Build broadcast') {
            steps {
                // Build the Spring Boot application using Maven
                sh 'cd broadcast && mvn clean package -DskipTests'
            }
        }
	
	 stage('Deploy broadcast') {
             steps {

                 sh "ssh root@103.255.224.46 'cd /root'"
                 sh "ssh root@103.255.224.46 'rm -rf broadcast || true'"
                 sh "ssh root@103.255.224.46 'mkdir broadcast'"
                 
                 sh 'scp -i id_rsa /var/jenkins_home/workspace/broadcast/broadcast/target/broadcast.jar root@103.255.224.46:~/broadcast/'
                 sh 'scp -i id_rsa /var/jenkins_home/workspace/broadcast/broadcast/Dockerfile root@103.255.224.46:~/broadcast/'

		 sh "ssh root@103.255.224.46 'docker service rm bricknetstack_broadcast || true'"
                 sh "ssh root@103.255.224.46 'docker stop root_broadcast_1 || true'"
                 sh "ssh root@103.255.224.46 'docker rm root_broadcast_1 || true'"
                 sh "ssh root@103.255.224.46 'docker rmi root_broadcast_1 || true'"
                 sh "ssh root@103.255.224.46 'docker build -t root_broadcast_1 /root/broadcast'"
                 // sh "ssh root@103.255.224.46 'docker run -it -d -p 8923:8923 --network=root_default --name root_broadcast_1 root_broadcast_1'"
                 sh "ssh root@103.255.224.46 'docker service create -d -p 8923:8923 --replicas 2 --network=bricknetstack_default --name bricknetstack_broadcast root_broadcast_1'"
             }
         }        
	
     }
     
  }   
