pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                // Checkout the source code from the repository
                checkout scm
            }
        }


         stage('Build notification') {
            steps {
                // Build the Spring Boot application using Maven
                sh 'cd notification && mvn clean package -DskipTests'
            }
        }
	
	 stage('Deploy notification') {
             steps {

                 sh "ssh root@192.168.0.9 'cd /root'"
                 sh "ssh root@192.168.0.9 'rm -rf notification || true'"
                 sh "ssh root@192.168.0.9 'mkdir notification'"
                 
                 sh 'scp -i id_rsa /var/jenkins_home/workspace/notification/notification/target/notification.jar root@192.168.0.9:~/notification/'
                 sh 'scp -i id_rsa /var/jenkins_home/workspace/notification/notification/Dockerfile root@192.168.0.9:~/notification/'

                 sh "ssh root@192.168.0.9 'docker stop root_notification_1 || true'"
                 sh "ssh root@192.168.0.9 'docker rm root_notification_1 || true'"
                 sh "ssh root@192.168.0.9 'docker rmi root_notification_1 || true'"
                 sh "ssh root@192.168.0.9 'docker build -t root_notification_1 /root/notification'"
                 sh "ssh root@192.168.0.9 'docker run -it -d -p 8084:8084 --network=root_default --name root_notification_1 root_notification_1'"
             }
         }        
	
     }
     
  }   
